In [1]:
import numpy as np
import cv2 as cv
import matplotlib.pyplot as plt
import pandas as pd
import os

import cvTools.interaction as cvi
import cvTools.segmentation as cvs
import extractor as ex
from tqdm import tqdm

In [34]:
data_path = os.path.expanduser('~/uni/Computer-Vision/data/')
data = pd.read_csv(f'{data_path}ISIC_2019_GroundTruth.csv', index_col='image', dtype={'image':str, 'MEL':bool, 'NV':bool}).drop(columns='NV')
for Type in ('MEL/', 'NV/'):
    with os.scandir(data_path + Type) as Dir:
        for entry in Dir:
            print(entry.path)

/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000002.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000004.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000013.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000022_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000026_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000029_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000030_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000031_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000035_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000036_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000040_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000043_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000046_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000049_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000054_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000056_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000074.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000077_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000078_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000139_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000140_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000141_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000142_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000143_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000145_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000146_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000147_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000148_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000149_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000150_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000151_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000152_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000153_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000154_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000155_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000156_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000157.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000159.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000160.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000161.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000162.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000163.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000164.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000165.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000166.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000167.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000169.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000170.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000171.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000172.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000173.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000174.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000175.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000176_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000276.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000277.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000278.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000279.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000281.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000282.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000283.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000285.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000287.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000288.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000289.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000290.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000292.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000293.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000294.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000295.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000297.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000298.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000299.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000300.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000301.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000302.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000303.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000306.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000307.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000310.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000311.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000313.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000314.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000390_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000393_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000395_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000410_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000412_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000413_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000415_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000420_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000434_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000444_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000445_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000463_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000466.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000469.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000482.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000484.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000487.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000511.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000513.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000516.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000517.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000518.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000519_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000520_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000521_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000522.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000531.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000533.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000547.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000548.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000549.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000550.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000551.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000552.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000554.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0000555.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0001100_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0001102_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0001103_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0001105_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0001106_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0001118_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0001119_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0001126_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0001128_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0001131_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0001133_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0001134_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0001140_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0001142_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0001148_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0001152_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0009868.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0009882.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0009897.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0009898.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0009905.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0009910.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0009918.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0009927.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0009934.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0009950.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0009955.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0009960.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0009971.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0009992.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0009993.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010000.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010011.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010016.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010023.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010024.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010029.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010034.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010036.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010054.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010056.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010067.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010080.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010081.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010089.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010094.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010171.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010174.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010175.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010189.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010194.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010207.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010225.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010231.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010235.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010240.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010241.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010251.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010265.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010267.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010319.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010321.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010322.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010329.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010349.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010350.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010358.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010360.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010364.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010372.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010379.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010380.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010441.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010466.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010468.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010476.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010576.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010587.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010591.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010596.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010597.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010852.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010860.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010862.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0010863.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0011095.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0011099.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0011112.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0011118.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0011121.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0011125.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0011126.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0011128.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0011130.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0011132.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0011135.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0011136.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0011137.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0011139.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0011140.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0011151.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0011158.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0011161.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0011163.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0011166.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0011169.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0011176.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0011210.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0011295.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0011305.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0011315.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0011329.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0011334.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0011344.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0011348.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0011349.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0011350.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0011356.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0011366.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0011374.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0011387.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0011390.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0012099_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0012137_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0012151_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0012208_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0012258_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0012288_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0012290_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0012298_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0012348_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0012356_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0012369_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0012382_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0012391_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0012395_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0012425_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0012434_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0012435_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0012450_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0012512_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0012678_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0012701_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0012715_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0012749_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0012756_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0012758.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0012887_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0012930_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0012988_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0012989_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0012990_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013072_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013073_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013079_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013141_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013184_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013198_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013232_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013242_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013258_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013277_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013321_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013334_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013359_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013365_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013374_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013411_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013414_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013427_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013429_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013455_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013457_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013459_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013472_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013473_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013490_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013491_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013497_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013499_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013500_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013501_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013518_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013525_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013530_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013549_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013565_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013567_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013572_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013573_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013577_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013578_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013579_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013581_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013588_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013594_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013606_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013610_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013615_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013617_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013618_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013626_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013634_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013636_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013639_downsampled.jpg
/home/teo/uni/Computer-Vision/data/MEL/ISIC_0013644_downsampled.jpg

In [64]:
L_m = []
L_s = []
A_m = []
A_s = []
B_m = []
B_s = []
height = []
width = []
ver_symm = []
hor_symm = []
cent_symm = []
feat_num = []


img_path = 'data/MEL/ISIC_0000043_downsampled.jpg'
# def main(img_path):
img = cv.imread(img_path)[1:-1, 1:-1, :]  # some photos have white borders
lab = cv.cvtColor(img, cv.COLOR_BGR2LAB)

### trimming hair
lab = cv.dilate(lab, np.ones((3,3), dtype=np.uint8), iterations=2)
lab = cv.erode(lab, np.ones((3,3), dtype=np.uint8), iterations=2)

### CLAHE
clahe = cv.createCLAHE(clipLimit=1, tileGridSize=(10,10))
lab[..., 0] = clahe.apply(lab[..., 0])
bgr = cv.cvtColor(lab, cv.COLOR_LAB2BGR)
# cvi.show([img, cl], ['img', 'cl'])


## h thresholding
otsu, bgr = cvs.thresholding(bgr)

### kill small patches
conts, _ = cv.findContours(otsu, cv.RETR_LIST, cv.CHAIN_APPROX_SIMPLE)
contSave = cvs.counter(otsu, 1000)
if len(contSave) == 0: contSave = cvs.counter(otsu, 100)

otsu = np.zeros_like(otsu)
for cont in contSave: cv.drawContours(otsu, conts, cont, 255, -1)
rows = [cv.hasNonZero(otsu[i]) for i in range(otsu.shape[0])]
cols = [cv.hasNonZero(otsu[:,i]) for i in range(otsu.shape[1])]
bgr = (bgr[rows][:, cols]).copy()
otsu = (otsu[rows][:, cols]).copy()
bgr = cv.bitwise_and(bgr, bgr, mask=otsu)
lab = cv.cvtColor(bgr, cv.COLOR_BGR2LAB)

### Filtering
lab = cv.bilateralFilter(lab, d=30, sigmaColor=20, sigmaSpace=10)
sift = cv.SIFT_create()
kp, des = sift.detectAndCompute(lab[..., 0], otsu)
# bgr = cv.cvtColor(lab, cv.COLOR_LAB2BGR)
# out = np.copy(bgr)
# out = cv.drawKeypoints(bgr, kp, out, flags=cv.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)
# cvi.show([img, out], ['img', 'kp'])
means, stds = cv.meanStdDev(lab, mask=otsu)
active = cv.countNonZero(otsu)
vert = cv.flip(otsu, 0)
hor = cv.flip(otsu, 1)
center = cv.flip(hor, 0)
for axis, res in zip((vert, hor, center), (ver_symm, hor_symm, cent_symm)): res.append(cv.countNonZero(cv.bitwise_and(otsu, axis)) / active)
for i, channel in enumerate((L_m, A_m, B_m)): channel.append(means[i].item())
for i, channel in enumerate((L_s, A_s, B_s)): channel.append(stds[i].item())
height.append(otsu.shape[0])
width.append(otsu.shape[1])
feat_num.append(len(kp))

In [65]:
cvi.show([otsu])

In [44]:
means

array([[ 96.86333198],
       [153.28978841],
       [147.34134914]])

In [75]:
pd.DataFrame({
    'L_m': means[0],
    'L_s': stds[0],
    'A_m': means[1],
    'A_s': stds[1],
    'B_m': means[2],
    'B_s': stds[2]
    }, index=['ISIC_0012549_downsampled'])

,L_m,L_s,A_m,A_s,B_m,B_s
ISIC_0012549_downsampled,104.55938,34.166983,143.683893,6.005756,143.82989,8.142614

In [43]:
data

                MEL  boh
image
ISIC_0000000  False  NaN
ISIC_0000001  False  NaN
ISIC_0000002   True  NaN
ISIC_0000003  False  NaN
ISIC_0000004   True  NaN
...             ...  ...
ISIC_0073241   True  NaN
ISIC_0073244  False  NaN
ISIC_0073245  False  NaN
ISIC_0073249   True  NaN
ISIC_0073251  False  NaN

[17397 rows x 2 columns]

In [42]:
data.loc['ISIC_0012549_downsampled', 'boh'] = 2

In [36]:
cvi.show([img, cv.cvtColor(lab, cv.COLOR_LAB2BGR)], ['original', 'final'])

In [5]:
%%timeit
img_path = 'data/MEL/ISIC_0000140_downsampled.jpg'
img = cv.imread(img_path)[1:-1, 1:-1, :]  # some photos have white borders

lab = cv.cvtColor(img, cv.COLOR_BGR2LAB)
### trimming hair
lab = cv.dilate(lab, np.ones((3,3), dtype=np.uint8), iterations=2)
lab = cv.erode(lab, np.ones((3,3), dtype=np.uint8), iterations=2)

### CLAHE
clahe = cv.createCLAHE(clipLimit=1, tileGridSize=(10,10))
lab[..., 0] = clahe.apply(lab[..., 0])
bgr = cv.cvtColor(lab, cv.COLOR_LAB2BGR)
# cvi.show([img, cl], ['img', 'cl'])


## h thresholding
temp = cv.cvtColor(bgr, cv.COLOR_BGR2HSV)  # to img?
_, thresh = cv.threshold(temp[..., 0], 23, 255, cv.THRESH_BINARY_INV)
_, thresh2 = cv.threshold(temp[..., 0], 110, 255, cv.THRESH_BINARY)
thresh = cv.bitwise_or(thresh, thresh2)

### Segmentation
temp = cv.cvtColor(bgr, cv.COLOR_BGR2GRAY)
lens = np.zeros_like(temp)
cv.thresholdWithMask(temp, lens, thresh, 10, 255, cv.THRESH_BINARY)  # lens is the new mask of active pxs

rows = [cv.hasNonZero(lens[i]) for i in range(lens.shape[0])]
cols = [cv.hasNonZero(lens[:, i]) for i in range(lens.shape[1])]
lens = (lens[rows][:, cols])[40:-40, 40:-40].copy()
temp = (temp[rows][:, cols])[40:-40, 40:-40].copy()
bgr = (bgr[rows][:, cols])[40:-40, 40:-40, :]

## otsu
otsu = np.zeros_like(temp)
cv.thresholdWithMask(temp, otsu, lens, 0, 255, cv.THRESH_BINARY_INV + cv.THRESH_OTSU)

### kill small patches
conts, _ = cv.findContours(otsu, cv.RETR_LIST, cv.CHAIN_APPROX_SIMPLE)
cxs = []
cys = []
contSave = []
for i, cont in enumerate(conts):
    mom = cv.moments(cont)
    if mom['m00'] < 1000: continue  # Area    # not guf  or mom['m00'] > 15e4  might wanna go little by little down
    cx = int(mom['m10'] / mom['m00'])  # centroid position
    lim = otsu.shape[1] * .1
    if cx < lim or cx > otsu.shape[1] - lim: continue
    cy = int(mom['m01'] / mom['m00'])
    lim = otsu.shape[0] * .1
    if cy < lim or cy > otsu.shape[0] - lim: continue
    cxs.append(cx)
    cys.append(cy)
    contSave.append(i)

if len(contSave) != 0:
    otsu = np.zeros_like(otsu)
    for cont in contSave: cv.drawContours(otsu, conts, cont, 255, -1)
    rows = [cv.hasNonZero(otsu[i]) for i in range(otsu.shape[0])]
    cols = [cv.hasNonZero(otsu[:,i]) for i in range(otsu.shape[1])]
    bgr = (bgr[rows][:, cols]).copy()
    otsu = (otsu[rows][:, cols]).copy()
    seg = cv.bitwise_and(bgr, bgr, mask=otsu)
    segL = cv.cvtColor(seg, cv.COLOR_BGR2LAB)
    
    ### Filtering
    lab = cv.bilateralFilter(segL, d=30, sigmaColor=20, sigmaSpace=10)
else: print('Damn')
orb = cv.SIFT_create()
bgr = cv.cvtColor(lab, cv.COLOR_LAB2BGR)
kp, des = orb.detectAndCompute(lab[..., 0], otsu)
# cvi.show([img, cl_BGR], ['original', 'pre-processed'])
out = np.copy(bgr)
out = cv.drawKeypoints(bgr, kp, out, flags=cv.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)
# cvi.show([img, out], ['img', 'kp'])
means, stds = cv.meanStdDev(lab, mask=otsu)

322 ms ± 17.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [35]:
prova = otsu
active = cv.countNonZero(prova)
vert = cv.flip(prova, 0)
hor = cv.flip(prova, 1)
center = cv.flip(hor, 0)
for i in (vert, hor, center): print(cv.countNonZero(cv.bitwise_and(prova, i)) / active)

0.8298865910607072
0.6630522912711038
0.6532868065890081

In [37]:
otsu.shape

(594, 563)

# Pandas

In [8]:
import pandas as pd
import os

In [18]:
data = pd.read_csv('data/ISIC_2019_GroundTruth.csv', index_col='image', dtype={'image':str, 'MEL':bool, 'NV':bool}).drop(columns='NV')
# with os.scandir('data/MEL/') as Dir:
    # for entry in Dir:
# data[image]

In [26]:
data.index

Index(['ISIC_0000000', 'ISIC_0000001', 'ISIC_0000002', 'ISIC_0000003',
       'ISIC_0000004', 'ISIC_0000006', 'ISIC_0000007', 'ISIC_0000008',
       'ISIC_0000009', 'ISIC_0000010',
       ...
       'ISIC_0073231', 'ISIC_0073232', 'ISIC_0073237', 'ISIC_0073238',
       'ISIC_0073240', 'ISIC_0073241', 'ISIC_0073244', 'ISIC_0073245',
       'ISIC_0073249', 'ISIC_0073251'],
      dtype='object', name='image', length=17397)

In [25]:
type(data.loc['ISIC_0012549_downsampled'])

pandas.core.series.Series

In [82]:
img_path = 'data/MEL/ISIC_0000022_downsampled.jpg'
# def main(img_path):
img = cv.imread(img_path)[1:-1, 1:-1, :]  # some photos have white borders
lab = cv.cvtColor(img, cv.COLOR_BGR2LAB)

### trimming hair
lab = cv.dilate(lab, np.ones((3,3), dtype=np.uint8), iterations=2)
lab = cv.erode(lab, np.ones((3,3), dtype=np.uint8), iterations=2)

### CLAHE
clahe = cv.createCLAHE(clipLimit=1, tileGridSize=(10,10))
lab[..., 0] = clahe.apply(lab[..., 0])
bgr = cv.cvtColor(lab, cv.COLOR_LAB2BGR)
# cvi.show([img, cl], ['img', 'cl'])


## h thresholding
otsu, bgr = cvs.thresholding(bgr)

### kill small patches
conts, _ = cv.findContours(otsu, cv.RETR_LIST, cv.CHAIN_APPROX_SIMPLE)
contSave = cvs.counter(otsu, 1000)
if len(contSave) == 0: contSave = cvs.counter(otsu, 100)

otsu = np.zeros_like(otsu)
for cont in contSave: cv.drawContours(otsu, conts, cont, 255, -1)
rows = [cv.hasNonZero(otsu[i]) for i in range(otsu.shape[0])]
cols = [cv.hasNonZero(otsu[:,i]) for i in range(otsu.shape[1])]
bgr = (bgr[rows][:, cols]).copy()
otsu = (otsu[rows][:, cols]).copy()
bgr = cv.bitwise_and(bgr, bgr, mask=otsu)
lab = cv.cvtColor(bgr, cv.COLOR_BGR2LAB)

### Filtering
lab = cv.bilateralFilter(lab, d=30, sigmaColor=20, sigmaSpace=10)
sift = cv.SIFT_create()
# kp, des = sift.detectAndCompute(lab[..., 0], otsu)
kp = sift.detect(lab[..., 0], otsu)
bgr = cv.cvtColor(lab, cv.COLOR_LAB2BGR)
out = np.copy(bgr)
out = cv.drawKeypoints(bgr, kp, out, flags=cv.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)
cvi.show([img, out], ['img', 'kp'])
means, stds = cv.meanStdDev(lab, mask=otsu)